config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  resources :genres
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  resources :users
  get "signup" => "users#new"
  get "signin" => "sessions#new"
  resource :session, only: [:new, :create, :destroy]
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  before_save :set_slug

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:edit, :update, :show, :destroy]
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to(@genre, notice: "Genre successfully created!")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to(@genre, notice: "Genre successfully updated!")
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def show
    @movies = @genre.movies
  end

  def destroy
    @genre.destroy
    redirect_to(genres_path, status: :see_other, alert: "Genre successfully deleted!")
  end

  private

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>
  <%= render "shared/errors", object: genre %>
  
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit a Genre</h1>
<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1><%= pluralize(@genres.size, "Genre") %></h1>
<ul class="users">
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre %>
      created
      <%= time_ago_in_words(genre.created_at) %> ago
    </li>
  <% end %>
</ul>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to("Create a genre", new_genre_path, class: "button") %>
  </section>
<% end %>

app/views/genres/new.html.erb
<h1>Create a New Genre</h1>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<h2>Movies in this Genre:</h2>
<ul>
  <% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= main_image(movie) %>
    </div>
    <h2 class="d-flex justify-content-center"><%= link_to(movie.title, movie_path(movie)) %></h2>
    </section>
  <% end %>
</ul>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to("All Genres", genres_path, class: "button") %>
    <%= link_to("Create a genre", new_genre_path, class: "button") %>
    <%= link_to("Delete genre", genre_path(@genre), class: "button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }) %>
  </section>
<% end %>